name: CI

on: [push, pull_request]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - 27.1

    steps:
      - uses: actions/checkout@v1
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - name: test
        run: |
           mv -f ../.emacs.d $HOME/.emacs.d;
           emacs --no-init-file -batch --script $HOME/.emacs.d/test/init.el
