name: ci
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build-kernel:
    strategy:
        matrix:
           package:
           - emacs
           - emacs-nox
           - emacs-git
           - emacs-pgtk
           channel:
           - nixos-unstable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:${{matrix.channel}}
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Build
      run: nix build '.#${{matrix.package}}'
