name: ci
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    strategy:
        matrix:
           package:
           - emacs
           - emacs-nox
           - emacs-git
           - emacs-pgtk
           channel:
           - nixos-unstable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://releases.nixos.org/nix/nix-2.13.3/install
        nix_path: nixpkgs=channel:${{matrix.channel}}
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v12
      with:
        name: emacs-d
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Enable cache
      run: cachix use emacs-d
    - name: Build
      run: nix build '.#${{matrix.package}}'
    - name: Run
      run: nix run '.#${{matrix.package}}' -- --batch --load init.el
    - name: Push
      run:  nix path-info --all | cachix push emacs-d
